 services:
   app:
     image: mahmoudabdeldayem2003/usermicroservice:0.0.1
     ports:
       - 9090:9090
     environment:
       SPRING_DATASOURCE_URL : jdbc:mysql://db:3306/store
       SPRING_DATASOURCE_USERNAME : root
       SPRING_DATASOURCE_PASSWORD :
     depends_on:
       - db



   db:
     image: mysql
     environment:
       DATABASE_HOST: docker.mysql
       DATABASE_PORT: 3306
       MYSQL_ALLOW_EMPTY_PASSWORD: yes
       MYSQL_DATABASE: store
       MYSQL_USER: root
       MYSQL_PASSWORD: